//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


fn main() {
	let max = 4000000i;

	let mut previous_num = 1;
	let mut current_num = 1;
	let mut summation = 0;
	while(current_num < max)
	{
		let new_num = previous_num + current_num;
		if(new_num %2 == 0)
		{
			summation += new_num;
		}
		previous_num = current_num;
		current_num = new_num;
	}
	println!("Result is: {}", summation)
}
